# Generated by Django 4.0.4 on 2022-04-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_address_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(help_text='50 ta belgidan kup bulmasin', max_length=50, unique=True),
        ),
    ]
